import { PrivatePigeonStat } from './../entities/private-pigeon-stat';
const pigeonList: PrivatePigeonStat[] =
    [
        {
            type: 0,
            name: "Dummy pigeon",
            rank: 1,
            element: 1,
            attack: 2,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 2,
            defensevariance: 1,
            defenserandomness:0,
            energy: 5,
            feedcost: 5,
            droppingsminute: 1,
            droppingsminutevariance: 0,
            feathers: 1
        },
        {
            type: 1,
            name: "Small pigeon",
            rank: 1,
            element: 1,
            attack: 2,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 2,
            defensevariance: 1,
            defenserandomness:0,
            energy: 5,
            feedcost: 2,
            droppingsminute: 1,
            droppingsminutevariance: 0,
            feathers: 2
        },
        {
            type: 2,
            name: "Small pigeon",
            rank: 2,
            element: 1,
            attack: 3,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 3,
            defensevariance: 1,
            defenserandomness:0,
            energy: 7,
            feedcost: 3,
            droppingsminute: 3,
            droppingsminutevariance: 0,
            feathers: 3
        },
        {
            type: 3,
            name: "Small pigeon",
            rank: 3,
            element: 1,
            attack: 6,
            attackvariance: 2,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 5,
            defensevariance: 1,
            defenserandomness:0,
            energy: 12,
            feedcost: 5,
            droppingsminute: 5,
            droppingsminutevariance: 0,
            feathers: 5
        },
        {
            type: 4,
            name: "Small pigeon",
            rank: 4,
            element: 1,
            attack: 9,
            attackvariance: 2,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 7,
            defensevariance: 1,
            defenserandomness:0,
            energy: 18,
            feedcost: 8,
            droppingsminute: 7,
            droppingsminutevariance: 0,
            feathers: 10
        },
        {
            type: 5,
            name: "Small pigeon",
            rank: 5,
            element: 1,
            attack: 15,
            attackvariance: 3,
            attackrandomness: 2,
            shield: 0,
            shieldvariance: 0,
            defense: 10,
            defensevariance: 2,
            defenserandomness:0,
            energy: 25,
            feedcost: 10,
            droppingsminute: 9,
            droppingsminutevariance: 0,
            feathers: 20
        },
        {
            type: 6,
            name: "Fat pigeon",
            rank: 1,
            element: 1,
            attack: 1,
            attackvariance: 0,
            attackrandomness: 1,
            shield: 1,
            shieldvariance: 0,
            defense: 4,
            defensevariance: 1,
            defenserandomness:1,
            energy: 5,
            feedcost: 3,
            droppingsminute: 4,
            droppingsminutevariance: 1,
            feathers: 3
        },
        {
            type: 7,
            name: "Fat pigeon",
            rank: 2,
            element: 1,
            attack: 2,
            attackvariance: 0,
            attackrandomness: 0,
            shield: 2,
            shieldvariance: 0,
            defense: 6,
            defensevariance: 1,
            defenserandomness:1,
            energy: 8,
            feedcost: 5,
            droppingsminute: 6,
            droppingsminutevariance: 1,
            feathers: 5
        },
        {
            type: 8,
            name: "Fat pigeon",
            rank: 3,
            element: 1,
            attack: 3,
            attackvariance: 0,
            attackrandomness: 1,
            shield: 3,
            shieldvariance: 0,
            defense: 10,
            defensevariance: 2,
            defenserandomness:2,
            energy: 12,
            feedcost: 8,
            droppingsminute: 10,
            droppingsminutevariance: 2,
            feathers: 10
        },
        {
            type: 9,
            name: "Fat pigeon",
            rank: 4,
            element: 1,
            attack: 5,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 4,
            shieldvariance: 0,
            defense: 15,
            defensevariance: 3,
            defenserandomness:3,
            energy: 18,
            feedcost: 13,
            droppingsminute: 15,
            droppingsminutevariance: 3,
            feathers: 18
        }
        ,
        {
            type: 10,
            name: "Fat pigeon",
            rank: 5,
            element: 1,
            attack: 7,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 5,
            shieldvariance: 0,
            defense: 23,
            defensevariance: 4,
            defenserandomness:3,
            energy: 25,
            feedcost: 16,
            droppingsminute: 20,
            droppingsminutevariance: 4,
            feathers: 25
        },
        {
            type: 11,
            name: "Sneaky pigeon",
            rank: 1,
            element: 1,
            attack: 4,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 1,
            defensevariance: 1,
            defenserandomness:0,
            energy: 5,
            feedcost: 2,
            droppingsminute: 1,
            droppingsminutevariance: 0,
            feathers: 2
        },
        {
            type: 12,
            name: "Sneaky pigeon",
            rank: 2,
            element: 1,
            attack: 6,
            attackvariance: 2,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 2,
            defensevariance: 1,
            defenserandomness:0,
            energy: 8,
            feedcost: 4,
            droppingsminute: 2,
            droppingsminutevariance: 0,
            feathers: 3
        },
        {
            type: 13,
            name: "Sneaky pigeon",
            rank: 3,
            element: 1,
            attack: 9,
            attackvariance: 2,
            attackrandomness: 2,
            shield: 0,
            shieldvariance: 0,
            defense: 3,
            defensevariance: 1,
            defenserandomness:0,
            energy: 12,
            feedcost: 6,
            droppingsminute: 3,
            droppingsminutevariance: 0,
            feathers: 6
        },
        {
            type: 14,
            name: "Sneaky pigeon",
            rank: 4,
            element: 1,
            attack: 16,
            attackvariance: 3,
            attackrandomness: 3,
            shield: 0,
            shieldvariance: 0,
            defense: 4,
            defensevariance: 1,
            defenserandomness:0,
            energy: 18,
            feedcost: 8,
            droppingsminute: 5,
            droppingsminutevariance: 0,
            feathers: 10
        },
        {
            type: 15,
            name: "Sneaky pigeon",
            rank: 5,
            element: 1,
            attack: 23,
            attackvariance: 4,
            attackrandomness: 4,
            shield: 0,
            shieldvariance: 0,
            defense: 5,
            defensevariance: 1,
            defenserandomness:0,
            energy: 25,
            feedcost: 11,
            droppingsminute: 7,
            droppingsminutevariance: 0,
            feathers: 20
        },
        {
            type: 16,
            name: "Pigehugo",
            rank: 1,
            element: 1,
            attack: 0,
            attackvariance: 0,
            attackrandomness: 0,
            shield: 0,
            shieldvariance: 0,
            defense: 0,
            defensevariance: 0,
            defenserandomness:0,
            energy: 5,
            feedcost: 1,
            droppingsminute: 5,
            droppingsminutevariance: 0,
            feathers: 10
        },
        {
            type: 17,
            name: "Dummy pigeon",
            rank: 1,
            element: 1,
            attack: 2,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 2,
            defensevariance: 1,
            defenserandomness:0,
            energy: 5,
            feedcost: 5,
            droppingsminute: 1,
            droppingsminutevariance: 0,
            feathers: 1
        },
        {
            type: 18,
            name: "Dummy pigeon",
            rank: 1,
            element: 1,
            attack: 2,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 2,
            defensevariance: 1,
            defenserandomness:0,
            energy: 5,
            feedcost: 5,
            droppingsminute: 1,
            droppingsminutevariance: 0,
            feathers: 1
        },{
            type: 19,
            name: "Dummy pigeon",
            rank: 1,
            element: 1,
            attack: 2,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 2,
            defensevariance: 1,
            defenserandomness:0,
            energy: 5,
            feedcost: 5,
            droppingsminute: 1,
            droppingsminutevariance: 0,
            feathers: 1
        },{
            type: 20,
            name: "Dummy pigeon",
            rank: 1,
            element: 1,
            attack: 2,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 2,
            defensevariance: 1,
            defenserandomness:0,
            energy: 5,
            feedcost: 5,
            droppingsminute: 1,
            droppingsminutevariance: 0,
            feathers: 1
        },
        {
            type: 21,
            name: "Prince pigeon",
            rank: 1,
            element: 1,
            attack: 11,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 22,
            defensevariance: 4,
            defenserandomness:5,
            energy: 25,
            feedcost: 16,
            droppingsminute: 15,
            droppingsminutevariance: 4,
            feathers: 25
        },
        {
            type: 22,
            name: "Prince pigeon",
            rank: 2,
            element: 1,
            attack: 13,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 29,
            defensevariance: 4,
            defenserandomness:5,
            energy: 25,
            feedcost: 16,
            droppingsminute: 20,
            droppingsminutevariance: 4,
            feathers: 30
        },
        {
            type: 23,
            name: "Prince pigeon",
            rank: 3,
            element: 1,
            attack: 15,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 1,
            shieldvariance: 1,
            defense: 33,
            defensevariance: 4,
            defenserandomness:5,
            energy: 25,
            feedcost: 16,
            droppingsminute: 24,
            droppingsminutevariance: 4,
            feathers: 35
        },
        {
            type: 24,
            name: "Prince pigeon",
            rank: 4,
            element: 1,
            attack: 17,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 2,
            shieldvariance: 1,
            defense: 38,
            defensevariance: 4,
            defenserandomness:5,
            energy: 25,
            feedcost: 16,
            droppingsminute: 28,
            droppingsminutevariance: 4,
            feathers: 40
        },
        {
            type: 25,
            name: "Prince pigeon",
            rank: 5,
            element: 1,
            attack: 19,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 3,
            shieldvariance: 1,
            defense: 43,
            defensevariance: 4,
            defenserandomness:5,
            energy: 25,
            feedcost: 16,
            droppingsminute: 31,
            droppingsminutevariance: 4,
            feathers: 50
        },
        {
            type: 26,
            name: "Dangerous pigeon",
            rank: 1,
            element: 1,
            attack: 22,
            attackvariance: 4,
            attackrandomness: 5,
            shield: 0,
            shieldvariance: 0,
            defense: 11,
            defensevariance: 1,
            defenserandomness:1,
            energy: 25,
            feedcost: 16,
            droppingsminute: 12,
            droppingsminutevariance: 3,
            feathers: 22
        },
        {
            type: 27,
            name: "Dangerous pigeon",
            rank: 2,
            element: 1,
            attack: 29,
            attackvariance: 4,
            attackrandomness: 5,
            shield: 0,
            shieldvariance: 0,
            defense: 13,
            defensevariance: 1,
            defenserandomness:1,
            energy: 25,
            feedcost: 16,
            droppingsminute: 17,
            droppingsminutevariance: 3,
            feathers: 27
        },
        {
            type: 28,
            name: "Dangerous pigeon",
            rank: 3,
            element: 1,
            attack: 33,
            attackvariance: 4,
            attackrandomness: 5,
            shield: 0,
            shieldvariance: 0,
            defense: 15,
            defensevariance: 1,
            defenserandomness:1,
            energy: 25,
            feedcost: 16,
            droppingsminute: 21,
            droppingsminutevariance: 3,
            feathers: 30
        },
        {
            type: 29,
            name: "Dangerous pigeon",
            rank: 4,
            element: 1,
            attack: 38,
            attackvariance: 4,
            attackrandomness: 5,
            shield: 0,
            shieldvariance: 0,
            defense: 16,
            defensevariance: 1,
            defenserandomness:1,
            energy: 25,
            feedcost: 16,
            droppingsminute: 23,
            droppingsminutevariance: 3,
            feathers: 35
        },
        {
            type: 30,
            name: "Dangerous pigeon",
            rank: 5,
            element: 1,
            attack: 43,
            attackvariance: 4,
            attackrandomness: 5,
            shield: 0,
            shieldvariance: 0,
            defense: 17,
            defensevariance: 1,
            defenserandomness:1,
            energy: 25,
            feedcost: 16,
            droppingsminute: 26,
            droppingsminutevariance: 3,
            feathers: 44
        },
        {
            type: 31,
            name: "Protector pigeon",
            rank: 1,
            element: 1,
            attack: 15,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 1,
            shieldvariance: 0,
            defense: 42,
            defensevariance: 4,
            defenserandomness:3,
            energy: 25,
            feedcost: 16,
            droppingsminute: 25,
            droppingsminutevariance: 3,
            feathers: 45
        },
        {
            type: 32,
            name: "Protector pigeon",
            rank: 2,
            element: 1,
            attack: 16,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 1,
            shieldvariance: 1,
            defense: 46,
            defensevariance: 4,
            defenserandomness:3,
            energy: 25,
            feedcost: 16,
            droppingsminute: 28,
            droppingsminutevariance: 3,
            feathers: 49
        },{
            type: 33,
            name: "Protector pigeon",
            rank: 3,
            element: 1,
            attack: 17,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 2,
            shieldvariance: 1,
            defense: 50,
            defensevariance: 4,
            defenserandomness:3,
            energy: 25,
            feedcost: 16,
            droppingsminute: 30,
            droppingsminutevariance: 3,
            feathers: 55
        },{
            type: 34,
            name: "Protector pigeon",
            rank: 4,
            element: 1,
            attack: 18,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 3,
            shieldvariance: 1,
            defense: 55,
            defensevariance: 4,
            defenserandomness:3,
            energy: 25,
            feedcost: 16,
            droppingsminute: 33,
            droppingsminutevariance: 3,
            feathers: 60
        },{
            type: 35,
            name: "Protector pigeon",
            rank: 5,
            element: 1,
            attack: 19,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 4,
            shieldvariance: 1,
            defense: 62,
            defensevariance: 4,
            defenserandomness:3,
            energy: 25,
            feedcost: 16,
            droppingsminute: 35,
            droppingsminutevariance: 3,
            feathers: 70
        },
        {
            type: 36,
            name: "Assassin pigeon",
            rank: 1,
            element: 1,
            attack: 42,
            attackvariance: 4,
            attackrandomness: 3,
            shield: 0,
            shieldvariance: 0,
            defense: 16,
            defensevariance: 1,
            defenserandomness:1,
            energy: 25,
            feedcost: 16,
            droppingsminute: 23,
            droppingsminutevariance: 3,
            feathers: 42
        },{
            type: 37,
            name: "Assassin pigeon",
            rank: 2,
            element: 1,
            attack: 46,
            attackvariance: 4,
            attackrandomness: 3,
            shield: 0,
            shieldvariance: 0,
            defense: 18,
            defensevariance: 1,
            defenserandomness:1,
            energy: 25,
            feedcost: 16,
            droppingsminute: 26,
            droppingsminutevariance: 3,
            feathers: 45
        },{
            type: 38,
            name: "Assassin pigeon",
            rank: 3,
            element: 1,
            attack: 50,
            attackvariance: 4,
            attackrandomness: 3,
            shield: 0,
            shieldvariance: 0,
            defense: 20,
            defensevariance: 1,
            defenserandomness:1,
            energy: 25,
            feedcost: 16,
            droppingsminute: 29,
            droppingsminutevariance: 3,
            feathers: 50
        },{
            type: 39,
            name: "Assassin pigeon",
            rank: 4,
            element: 1,
            attack: 55,
            attackvariance: 4,
            attackrandomness: 3,
            shield: 0,
            shieldvariance: 0,
            defense: 21,
            defensevariance: 1,
            defenserandomness:1,
            energy: 25,
            feedcost: 16,
            droppingsminute: 31,
            droppingsminutevariance: 3,
            feathers: 55
        },{
            type: 40,
            name: "Assassin pigeon",
            rank: 5,
            element: 1,
            attack: 62,
            attackvariance: 4,
            attackrandomness: 3,
            shield: 0,
            shieldvariance: 0,
            defense: 23,
            defensevariance: 1,
            defenserandomness:1,
            energy: 25,
            feedcost: 16,
            droppingsminute: 33,
            droppingsminutevariance: 3,
            feathers: 59
        },{
            type: 41,
            name: "Royal pigeon",
            rank: 1,
            element: 1,
            attack: 20,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 1,
            shieldvariance: 0,
            defense: 61,
            defensevariance: 4,
            defenserandomness:5,
            energy: 25,
            feedcost: 16,
            droppingsminute: 33,
            droppingsminutevariance: 5,
            feathers: 65
        },{
            type: 42,
            name: "Royal pigeon",
            rank: 2,
            element: 1,
            attack: 21,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 1,
            shieldvariance: 1,
            defense: 66,
            defensevariance: 4,
            defenserandomness:5,
            energy: 25,
            feedcost: 16,
            droppingsminute: 35,
            droppingsminutevariance: 5,
            feathers: 69
        },{
            type: 43,
            name: "Royal pigeon",
            rank: 3,
            element: 1,
            attack: 22,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 2,
            shieldvariance: 1,
            defense: 71,
            defensevariance: 4,
            defenserandomness:5,
            energy: 25,
            feedcost: 16,
            droppingsminute: 41,
            droppingsminutevariance: 5,
            feathers: 72
        },{
            type: 44,
            name: "Royal pigeon",
            rank: 4,
            element: 1,
            attack: 23,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 3,
            shieldvariance: 1,
            defense: 79,
            defensevariance: 4,
            defenserandomness:5,
            energy: 25,
            feedcost: 16,
            droppingsminute: 43,
            droppingsminutevariance: 5,
            feathers: 75
        },{
            type: 45,
            name: "Royal pigeon",
            rank: 5,
            element: 1,
            attack: 24,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 4,
            shieldvariance: 1,
            defense: 90,
            defensevariance: 4,
            defenserandomness:5,
            energy: 25,
            feedcost: 16,
            droppingsminute: 46,
            droppingsminutevariance: 5,
            feathers: 80
        },{
            type: 46,
            name: "Killer pigeon",
            rank: 1,
            element: 1,
            attack: 61,
            attackvariance: 4,
            attackrandomness: 5,
            shield: 0,
            shieldvariance: 0,
            defense: 21,
            defensevariance: 1,
            defenserandomness:1,
            energy: 25,
            feedcost: 16,
            droppingsminute: 32,
            droppingsminutevariance: 5,
            feathers: 65
        },{
            type: 47,
            name: "Killer pigeon",
            rank: 2,
            element: 1,
            attack: 66,
            attackvariance: 4,
            attackrandomness: 5,
            shield: 0,
            shieldvariance: 0,
            defense: 22,
            defensevariance: 1,
            defenserandomness:1,
            energy: 25,
            feedcost: 16,
            droppingsminute: 34,
            droppingsminutevariance: 5,
            feathers: 69
        },{
            type: 48,
            name: "Killer pigeon",
            rank: 3,
            element: 1,
            attack: 71,
            attackvariance: 4,
            attackrandomness: 5,
            shield: 0,
            shieldvariance: 0,
            defense: 23,
            defensevariance: 1,
            defenserandomness:1,
            energy: 25,
            feedcost: 16,
            droppingsminute: 40,
            droppingsminutevariance: 5,
            feathers: 72
        },{
            type: 49,
            name: "Killer pigeon",
            rank: 4,
            element: 1,
            attack: 79,
            attackvariance: 4,
            attackrandomness: 5,
            shield: 0,
            shieldvariance: 0,
            defense: 24,
            defensevariance: 1,
            defenserandomness:1,
            energy: 25,
            feedcost: 16,
            droppingsminute: 42,
            droppingsminutevariance: 5,
            feathers: 75
        },{
            type: 50,
            name: "Killer pigeon",
            rank: 5,
            element: 1,
            attack: 90,
            attackvariance: 4,
            attackrandomness: 5,
            shield: 1,
            shieldvariance: 0,
            defense: 25,
            defensevariance: 1,
            defenserandomness:1,
            energy: 25,
            feedcost: 16,
            droppingsminute: 45,
            droppingsminutevariance: 5,
            feathers: 80
        },{
            type: 51,
            name: "Crazy pigeon",
            rank: 1,
            element: 1,
            attack: 40,
            attackvariance: 20,
            attackrandomness: 15,
            shield: 1,
            shieldvariance: 1,
            defense: 40,
            defensevariance: 20,
            defenserandomness:15,
            energy: 25,
            feedcost: 16,
            droppingsminute: 21,
            droppingsminutevariance: 15,
            feathers: 1
        },{
            type: 52,
            name: "Crazy pigeon",
            rank: 2,
            element: 1,
            attack: 50,
            attackvariance: 20,
            attackrandomness: 15,
            shield: 1,
            shieldvariance: 1,
            defense: 50,
            defensevariance: 20,
            defenserandomness:15,
            energy: 25,
            feedcost: 16,
            droppingsminute: 21,
            droppingsminutevariance: 19,
            feathers: 1
        },{
            type: 53,
            name: "Crazy pigeon",
            rank: 3,
            element: 1,
            attack: 60,
            attackvariance: 20,
            attackrandomness: 15,
            shield: 2,
            shieldvariance: 2,
            defense: 60,
            defensevariance: 20,
            defenserandomness:15,
            energy: 25,
            feedcost: 16,
            droppingsminute: 23,
            droppingsminutevariance: 19,
            feathers: 1
        },{
            type: 54,
            name: "Crazy pigeon",
            rank: 4,
            element: 1,
            attack: 75,
            attackvariance: 20,
            attackrandomness: 15,
            shield: 3,
            shieldvariance: 3,
            defense: 75,
            defensevariance: 20,
            defenserandomness:15,
            energy: 25,
            feedcost: 16,
            droppingsminute: 25,
            droppingsminutevariance: 19,
            feathers: 1
        },{
            type: 55,
            name: "Crazy pigeon",
            rank: 5,
            element: 1,
            attack: 100,
            attackvariance: 20,
            attackrandomness: 15,
            shield: 3,
            shieldvariance: 3,
            defense: 100,
            defensevariance: 20,
            defenserandomness:15,
            energy: 25,
            feedcost: 16,
            droppingsminute: 27,
            droppingsminutevariance: 19,
            feathers: 1
        },{
            type: 56,
            name: "Dummy pigeon",
            rank: 5,
            element: 1,
            attack: 75,
            attackvariance: 20,
            attackrandomness: 15,
            shield: 3,
            shieldvariance: 3,
            defense: 75,
            defensevariance: 20,
            defenserandomness:15,
            energy: 25,
            feedcost: 16,
            droppingsminute: 25,
            droppingsminutevariance: 19,
            feathers: 1
        },{
            type: 57,
            name: "Dummy pigeon",
            rank: 5,
            element: 1,
            attack: 75,
            attackvariance: 20,
            attackrandomness: 15,
            shield: 3,
            shieldvariance: 3,
            defense: 75,
            defensevariance: 20,
            defenserandomness:15,
            energy: 25,
            feedcost: 16,
            droppingsminute: 25,
            droppingsminutevariance: 19,
            feathers: 1
        },{
            type: 58,
            name: "Dummy pigeon",
            rank: 5,
            element: 1,
            attack: 75,
            attackvariance: 20,
            attackrandomness: 15,
            shield: 3,
            shieldvariance: 3,
            defense: 75,
            defensevariance: 20,
            defenserandomness:15,
            energy: 25,
            feedcost: 16,
            droppingsminute: 25,
            droppingsminutevariance: 19,
            feathers: 1
        },{
            type: 59,
            name: "Dummy pigeon",
            rank: 5,
            element: 1,
            attack: 75,
            attackvariance: 20,
            attackrandomness: 15,
            shield: 3,
            shieldvariance: 3,
            defense: 75,
            defensevariance: 20,
            defenserandomness:15,
            energy: 25,
            feedcost: 16,
            droppingsminute: 25,
            droppingsminutevariance: 19,
            feathers: 1
        },{
            type: 60,
            name: "Dummy pigeon",
            rank: 5,
            element: 1,
            attack: 75,
            attackvariance: 20,
            attackrandomness: 15,
            shield: 3,
            shieldvariance: 3,
            defense: 75,
            defensevariance: 20,
            defenserandomness:15,
            energy: 25,
            feedcost: 16,
            droppingsminute: 25,
            droppingsminutevariance: 19,
            feathers: 1
        },{
            type: 61,
            name: "Savior pigeon",
            rank: 1,
            element: 1,
            attack: 25,
            attackvariance: 2,
            attackrandomness: 1,
            shield: 1,
            shieldvariance: 1,
            defense: 89,
            defensevariance: 5,
            defenserandomness:5,
            energy: 25,
            feedcost: 16,
            droppingsminute: 44,
            droppingsminutevariance: 5,
            feathers: 75
        },{
            type: 62,
            name: "Savior pigeon",
            rank: 2,
            element: 1,
            attack: 26,
            attackvariance: 2,
            attackrandomness: 1,
            shield: 1,
            shieldvariance: 1,
            defense: 94,
            defensevariance: 5,
            defenserandomness:5,
            energy: 25,
            feedcost: 16,
            droppingsminute: 45,
            droppingsminutevariance: 5,
            feathers: 78
        },{
            type: 63,
            name: "Savior pigeon",
            rank: 3,
            element: 1,
            attack: 27,
            attackvariance: 2,
            attackrandomness: 1,
            shield: 2,
            shieldvariance: 1,
            defense: 100,
            defensevariance: 5,
            defenserandomness:5,
            energy: 25,
            feedcost: 16,
            droppingsminute: 48,
            droppingsminutevariance: 5,
            feathers: 80
        },{
            type: 64,
            name: "Savior pigeon",
            rank: 4,
            element: 1,
            attack: 28,
            attackvariance: 2,
            attackrandomness: 1,
            shield: 2,
            shieldvariance: 1,
            defense: 106,
            defensevariance: 5,
            defenserandomness:5,
            energy: 25,
            feedcost: 16,
            droppingsminute: 51,
            droppingsminutevariance: 5,
            feathers: 85
        },{
            type: 65,
            name: "Savior pigeon",
            rank: 5,
            element: 1,
            attack: 29,
            attackvariance: 2,
            attackrandomness: 1,
            shield: 3,
            shieldvariance: 1,
            defense: 112,
            defensevariance: 6,
            defenserandomness:5,
            energy: 25,
            feedcost: 16,
            droppingsminute: 55,
            droppingsminutevariance: 5,
            feathers: 90
        },{
            type: 66,
            name: "Eradicator pigeon",
            rank: 1,
            element: 1,
            attack: 89,
            attackvariance: 5,
            attackrandomness: 5,
            shield: 0,
            shieldvariance: 0,
            defense: 25,
            defensevariance: 2,
            defenserandomness:1,
            energy: 25,
            feedcost: 16,
            droppingsminute: 40,
            droppingsminutevariance: 5,
            feathers: 78
        },{
            type: 67,
            name: "Eradicator pigeon",
            rank: 2,
            element: 1,
            attack: 94,
            attackvariance: 5,
            attackrandomness: 5,
            shield: 0,
            shieldvariance: 0,
            defense: 26,
            defensevariance: 2,
            defenserandomness:1,
            energy: 25,
            feedcost: 16,
            droppingsminute: 42,
            droppingsminutevariance: 5,
            feathers: 82
        },{
            type: 68,
            name: "Eradicator pigeon",
            rank: 3,
            element: 1,
            attack: 100,
            attackvariance: 5,
            attackrandomness: 5,
            shield: 0,
            shieldvariance: 0,
            defense: 27,
            defensevariance: 2,
            defenserandomness:1,
            energy: 25,
            feedcost: 16,
            droppingsminute: 44,
            droppingsminutevariance: 5,
            feathers: 85
        },{
            type: 69,
            name: "Eradicator pigeon",
            rank: 4,
            element: 1,
            attack: 106,
            attackvariance: 5,
            attackrandomness: 5,
            shield: 0,
            shieldvariance: 0,
            defense: 28,
            defensevariance: 2,
            defenserandomness:1,
            energy: 25,
            feedcost: 16,
            droppingsminute: 46,
            droppingsminutevariance: 5,
            feathers: 90
        },{
            type: 70,
            name: "Eradicator pigeon",
            rank: 5,
            element: 1,
            attack: 112,
            attackvariance: 6,
            attackrandomness: 5,
            shield: 1,
            shieldvariance: 0,
            defense: 29,
            defensevariance: 2,
            defenserandomness:1,
            energy: 25,
            feedcost: 16,
            droppingsminute: 49,
            droppingsminutevariance: 5,
            feathers: 95
        }
    ]

export default pigeonList;
