const pigeonList =
    [{
        id: 0,
        name:"Petit pigeon commun",
        rank: 1,
        attack: 2,
        attackvariance: 1,
        defense: 1,
        defensevariance: 0,
        life: 3,
        lifevariance: 1,
        droppingsminute: 1,
        droppingsminutevariance: 0,
        feathers: 2
    }, {
        id: 1,
        name:"Petit pigeon atypique",
        rank: 2,
        attack: 3,
        attackvariance: 1,
        defense: 2,
        defensevariance: 1,
        life: 4,
        lifevariance: 1,
        droppingsminute: 1,
        droppingsminutevariance: 0,
        feathers: 2
    }, {
        id: 2,
        name:"Petit pigeon rare",
        rank: 3,
        attack: 5,
        attackvariance: 1,
        defense: 3,
        defensevariance: 1,
        life: 7,
        lifevariance: 1,
        droppingsminute: 2,
        droppingsminutevariance: 0,
        feathers: 3
    }, {
        id: 3,
        name:"Petit pigeon épique",
        rank: 4,
        attack: 7,
        attackvariance: 2,
        defense: 4,
        defensevariance: 2,
        life: 10,
        lifevariance: 2,
        droppingsminute: 2,
        droppingsminutevariance: 1,
        feathers: 4
    }, {
        id: 4,
        name:"Petit pigeon légendaire",
        rank: 5,
        attack: 9,
        attackvariance: 3,
        defense: 5,
        defensevariance: 2,
        life: 11,
        lifevariance: 2,
        droppingsminute: 2,
        droppingsminutevariance: 1,
        feathers: 4
    },{
        id: 5,
        name:"Gros pigeon commun",
        rank: 1,
        attack: 1,
        attackvariance: 0,
        defense: 2,
        defensevariance: 1,
        life: 4,
        lifevariance: 1,
        droppingsminute: 2,
        droppingsminutevariance: 0,
        feathers: 2
    },{
        id: 6,
        name:"Gros pigeon atypique",
        rank: 2,
        attack: 1,
        attackvariance: 0,
        defense: 4,
        defensevariance: 1,
        life: 6,
        lifevariance: 1,
        droppingsminute: 4,
        droppingsminutevariance: 1,
        feathers: 3
    },{
        id: 7,
        name:"Gros pigeon rare",
        rank: 3,
        attack: 2,
        attackvariance: 1,
        defense: 6,
        defensevariance: 2,
        life: 7,
        lifevariance: 2,
        droppingsminute: 5,
        droppingsminutevariance: 1,
        feathers: 3
    },{
        id: 8,
        name:"Gros pigeon épique",
        rank: 4,
        attack: 3,
        attackvariance: 1,
        defense: 8,
        defensevariance: 2,
        life: 9,
        lifevariance: 2,
        droppingsminute: 6,
        droppingsminutevariance: 1,
        feathers: 4
    },{
        id: 9,
        name:"Gros pigeon légendaire",
        rank: 5,
        attack: 4,
        attackvariance: 1,
        defense: 10,
        defensevariance: 2,
        life: 10,
        lifevariance: 2,
        droppingsminute: 7,
        droppingsminutevariance: 1,
        feathers: 5
    },
]

export default pigeonList;
