import { PrivatePigeonStat } from './../entities/private-pigeon-stat';
const pigeonList: PrivatePigeonStat[] =
    [
        {
            type: 0,
            name: "Small common pigeon",
            rank: 1,
            element: 1,
            attack: 2,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 2,
            defensevariance: 1,
            defenserandomness:0,
            energy: 5,
            feedcost: 5,
            droppingsminute: 1,
            droppingsminutevariance: 0,
            feathers: 1
        },
        {
            type: 1,
            name: "Small uncommon pigeon",
            rank: 2,
            element: 1,
            attack: 2,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 2,
            defensevariance: 1,
            defenserandomness:0,
            energy: 5,
            feedcost: 5,
            droppingsminute: 1,
            droppingsminutevariance: 0,
            feathers: 2
        },
        {
            type: 2,
            name: "Small rare pigeon",
            rank: 3,
            element: 1,
            attack: 2,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 2,
            defensevariance: 1,
            defenserandomness:0,
            energy: 5,
            feedcost: 5,
            droppingsminute: 1,
            droppingsminutevariance: 0,
            feathers: 3
        },
        {
            type: 3,
            name: "Small epic pigeon",
            rank: 4,
            element: 1,
            attack: 2,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 2,
            defensevariance: 1,
            defenserandomness:0,
            energy: 5,
            feedcost: 5,
            droppingsminute: 1,
            droppingsminutevariance: 0,
            feathers: 5
        },
        {
            type: 4,
            name: "Small legendary pigeon",
            rank: 5,
            element: 1,
            attack: 2,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 2,
            defensevariance: 1,
            defenserandomness:0,
            energy: 5,
            feedcost: 5,
            droppingsminute: 1,
            droppingsminutevariance: 0,
            feathers: 10
        },
        {
            type: 5,
            name: "Fat common pigeon",
            rank: 1,
            element: 1,
            attack: 2,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 2,
            defensevariance: 1,
            defenserandomness:0,
            energy: 5,
            feedcost: 5,
            droppingsminute: 1,
            droppingsminutevariance: 0,
            feathers: 2
        },
        {
            type: 6,
            name: "Fat uncommon pigeon",
            rank: 2,
            element: 1,
            attack: 2,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 2,
            defensevariance: 1,
            defenserandomness:0,
            energy: 5,
            feedcost: 5,
            droppingsminute: 1,
            droppingsminutevariance: 0,
            feathers: 2
        },
        {
            type: 7,
            name: "Fat rare pigeon",
            rank: 3,
            element: 1,
            attack: 2,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 2,
            defensevariance: 1,
            defenserandomness:0,
            energy: 5,
            feedcost: 5,
            droppingsminute: 1,
            droppingsminutevariance: 0,
            feathers: 2
        },
        {
            type: 8,
            name: "Fat epic pigeon",
            rank: 4,
            element: 1,
            attack: 2,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 2,
            defensevariance: 1,
            defenserandomness:0,
            energy: 5,
            feedcost: 5,
            droppingsminute: 1,
            droppingsminutevariance: 0,
            feathers: 2
        }
        ,
        {
            type: 9,
            name: "Fat legendary pigeon",
            rank: 5,
            element: 1,
            attack: 2,
            attackvariance: 1,
            attackrandomness: 1,
            shield: 0,
            shieldvariance: 0,
            defense: 2,
            defensevariance: 1,
            defenserandomness:0,
            energy: 5,
            feedcost: 5,
            droppingsminute: 1,
            droppingsminutevariance: 0,
            feathers: 2
        }
    ]

export default pigeonList;
